#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
a=0
while [ $a -lt 10 ]
do
      if [ $a -eq 8 ]
      then
            echo "Best School"
            echo "Hi"
            a=`expr $a + 1`
      else
            echo "Best School"
            a=`expr $a + 1`
      fi
done